del *.bak


copy c:\temp\snapshot\au-med-k-actual.xml au-med-k-expected.xml
copy c:\temp\snapshot\au3-actual.xml au3-expected.xml
copy c:\temp\snapshot\ca-patient-actual.xml ca-patient-expected.xml
copy c:\temp\snapshot\dk1-actual.xml dk1-expected.xml
copy c:\temp\snapshot\dv1-actual.xml dv1-expected.xml
copy c:\temp\snapshot\ext-sort-issue-actual.xml ext-sort-issue-expected.xml
copy c:\temp\snapshot\logical1-actual.xml logical1-expected.xml
copy c:\temp\snapshot\logical2-actual.xml logical2-expected.xml
copy c:\temp\snapshot\medstmt-ips-actual.xml medstmt-ips-expected.xml
copy c:\temp\snapshot\medstmt-nsw-actual.xml medstmt-nsw-expected.xml
copy c:\temp\snapshot\nl-med-actual.xml nl-med-expected.xml
copy c:\temp\snapshot\obs-1-1-actual.xml obs-1-1-expected.xml
copy c:\temp\snapshot\obs-1-actual.xml obs-1-expected.xml
copy c:\temp\snapshot\obs-2-1-actual.xml obs-2-1-expected.xml
copy c:\temp\snapshot\obs-2-2-actual.xml obs-2-2-expected.xml
copy c:\temp\snapshot\obs-2-actual.xml obs-2-expected.xml
copy c:\temp\snapshot\obs-2a-actual.xml obs-2a-expected.xml
copy c:\temp\snapshot\obs-2b-actual.xml obs-2b-expected.xml
copy c:\temp\snapshot\obs-4-actual.xml obs-4-expected.xml
copy c:\temp\snapshot\obs-badfixed-actual.xml obs-badfixed-expected.xml
copy c:\temp\snapshot\obs-badpattern-actual.xml obs-badpattern-expected.xml
copy c:\temp\snapshot\obs-rebind-actual.xml obs-rebind-expected.xml
copy c:\temp\snapshot\pat-choice-ms-actual.xml pat-choice-ms-expected.xml
copy c:\temp\snapshot\pat-msonslice-actual.xml pat-msonslice-expected.xml
copy c:\temp\snapshot\pat-msonslice1-actual.xml pat-msonslice1-expected.xml
copy c:\temp\snapshot\pattern-ext-1-actual.xml pattern-ext-1-expected.xml
copy c:\temp\snapshot\pattern-ext-2-actual.xml pattern-ext-2-expected.xml
copy c:\temp\snapshot\samply1-actual.xml samply1-expected.xml
copy c:\temp\snapshot\sushi1-actual.xml sushi1-expected.xml
copy c:\temp\snapshot\sushi2-actual.xml sushi2-expected.xml
copy c:\temp\snapshot\sushi3-actual.xml sushi3-expected.xml
copy c:\temp\snapshot\t1-actual.xml t1-expected.xml
copy c:\temp\snapshot\t2-actual.xml t2-expected.xml
copy c:\temp\snapshot\t3-actual.xml t3-expected.xml
copy c:\temp\snapshot\t4-actual.xml t4-expected.xml
copy c:\temp\snapshot\t4a-actual.xml t4a-expected.xml
copy c:\temp\snapshot\t5-actual.xml t5-expected.xml
copy c:\temp\snapshot\au1-actual.xml au1-expected.xml
copy c:\temp\snapshot\au2-actual.xml au2-expected.xml
copy c:\temp\snapshot\t10-actual.xml t10-expected.xml
copy c:\temp\snapshot\t11-actual.xml t11-expected.xml
copy c:\temp\snapshot\t12-actual.xml t12-expected.xml
copy c:\temp\snapshot\t12a-actual.xml t12a-expected.xml
copy c:\temp\snapshot\t13-actual.xml t13-expected.xml
copy c:\temp\snapshot\t14-actual.xml t14-expected.xml
copy c:\temp\snapshot\t15-actual.xml t15-expected.xml
copy c:\temp\snapshot\t16-actual.xml t16-expected.xml
copy c:\temp\snapshot\t17-actual.xml t17-expected.xml
copy c:\temp\snapshot\t18-actual.xml t18-expected.xml
copy c:\temp\snapshot\t19-actual.xml t19-expected.xml
copy c:\temp\snapshot\t21-actual.xml t21-expected.xml
copy c:\temp\snapshot\t22-actual.xml t22-expected.xml
copy c:\temp\snapshot\t23-actual.xml t23-expected.xml
copy c:\temp\snapshot\t24a-actual.xml t24a-expected.xml
copy c:\temp\snapshot\t24b-actual.xml t24b-expected.xml
copy c:\temp\snapshot\t26-actual.xml t26-expected.xml
copy c:\temp\snapshot\t27-actual.xml t27-expected.xml
copy c:\temp\snapshot\t28-actual.xml t28-expected.xml
copy c:\temp\snapshot\t29-actual.xml t29-expected.xml
copy c:\temp\snapshot\t30b-actual.xml t30b-expected.xml
copy c:\temp\snapshot\t31-actual.xml t31-expected.xml
copy c:\temp\snapshot\t32-actual.xml t32-expected.xml
copy c:\temp\snapshot\t33-actual.xml t33-expected.xml
copy c:\temp\snapshot\t34-actual.xml t34-expected.xml
copy c:\temp\snapshot\t35-actual.xml t35-expected.xml
copy c:\temp\snapshot\t36-actual.xml t36-expected.xml
copy c:\temp\snapshot\t38-actual.xml t38-expected.xml
copy c:\temp\snapshot\t40-actual.xml t40-expected.xml
copy c:\temp\snapshot\t41-actual.xml t41-expected.xml
copy c:\temp\snapshot\t42-actual.xml t42-expected.xml
copy c:\temp\snapshot\t43-actual.xml t43-expected.xml
copy c:\temp\snapshot\t44-actual.xml t44-expected.xml
copy c:\temp\snapshot\t44a-actual.xml t44a-expected.xml
copy c:\temp\snapshot\t45-actual.xml t45-expected.xml
copy c:\temp\snapshot\t6-actual.xml t6-expected.xml
copy c:\temp\snapshot\t7-actual.xml t7-expected.xml
copy c:\temp\snapshot\t8-actual.xml t8-expected.xml
copy c:\temp\snapshot\t9-actual.xml t9-expected.xml

pause